In [1]:
import pandas as pd
import numpy as np

In [2]:
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

In [3]:
df.sort_index(ascending=False)

                   A         B         C         D
2013-01-06  1.146309  0.430701 -0.068969  1.339589
2013-01-05  0.586185  2.594636 -1.429697  0.711884
2013-01-04  1.187345 -0.581625  0.230563 -1.765546
2013-01-03  1.702733 -0.316858  1.380734 -0.786633
2013-01-02  0.705577  0.076015 -1.107854 -1.104739
2013-01-01  0.393683  0.834596  0.459223  0.163929

In [4]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01  0.163929  0.459223  0.834596  0.393683
2013-01-02 -1.104739 -1.107854  0.076015  0.705577
2013-01-03 -0.786633  1.380734 -0.316858  1.702733
2013-01-04 -1.765546  0.230563 -0.581625  1.187345
2013-01-05  0.711884 -1.429697  2.594636  0.586185
2013-01-06  1.339589 -0.068969  0.430701  1.146309

In [5]:
dataset3 = pd.read_csv("sample_dataset.utf8.csv", encoding="utf_8")

FileNotFoundError: File b'sample_dataset.utf8.csv' does not exist

In [6]:
dataset3 = pd.read_csv("sample.csv", encoding="utf_8")

In [7]:
dataset3

      yuma  M  A  九州   RC  武道
0      ren  M  S  東京   SI  武道
1   hiroto  M  A  関東  GOV  武道
2   sakura  F  C  関西  EDU  武道
3     yuna  F  A  関東  EDU  書道
4   haruto  M  B  中部   SI  書道
5   minato  M  C  山陽  GOV  書道
6      rin  F  C  関東   RC  書道
7      yui  F  S  関西  GOV  茶道
8     hina  F  B  中部   RC  茶道
9   himari  F  A  関東  EDU  茶道
10     yua  F  A  山陽   SI  茶道
11    riko  F  B  九州   SI  舞踊
12     mei  F  C  東北  GOV  舞踊
13    yota  M  S  東京  EDU  舞踊
14    yuto  M  B  関西   RC  舞踊
15   asahi  M  B  東京  GOV  古典
16    sota  M  B  九州  EDU  古典
17     aoi  F  C  東京   SI  古典
18  haruto  M  C  東北   RC  古典

In [8]:
dataset5 = pd.read_csv("sample.csv", encoding="utf_8")

In [9]:
dataset5

   name\tgender\tskill\tregion\tpresentation\tjf
0                         yuma\tM\tA\t九州\tRC\t武道
1                          ren\tM\tS\t東京\tSI\t武道
2                      hiroto\tM\tA\t関東\tGOV\t武道
3                      sakura\tF\tC\t関西\tEDU\t武道
4                        yuna\tF\tA\t関東\tEDU\t書道
5                       haruto\tM\tB\t中部\tSI\t書道
6                      minato\tM\tC\t山陽\tGOV\t書道
7                          rin\tF\tC\t関東\tRC\t書道
8                         yui\tF\tS\t関西\tGOV\t茶道
9                         hina\tF\tB\t中部\tRC\t茶道
10                     himari\tF\tA\t関東\tEDU\t茶道
11                         yua\tF\tA\t山陽\tSI\t茶道
12                        riko\tF\tB\t九州\tSI\t舞踊
13                        mei\tF\tC\t東北\tGOV\t舞踊
14                       yota\tM\tS\t東京\tEDU\t舞踊
15                        yuto\tM\tB\t関西\tRC\t舞踊
16                      asahi\tM\tB\t東京\tGOV\t古典
17                       sota\tM\tB\t九州\tEDU\t古典
18                         aoi\tF\tC\t東京\tSI\t古典
19                      haruto\tM\tC\t東北\tRC\t古典

In [10]:
dataset = pd.read_csv("sample.csv", encoding="utf_8")

In [11]:
dataset

      name gender skill region presentation  jf
0     yuma      M     A     九州           RC  武道
1      ren      M     S     東京           SI  武道
2   hiroto      M     A     関東          GOV  武道
3   sakura      F     C     関西          EDU  武道
4     yuna      F     A     関東          EDU  書道
5   haruto      M     B     中部           SI  書道
6   minato      M     C     山陽          GOV  書道
7      rin      F     C     関東           RC  書道
8      yui      F     S     関西          GOV  茶道
9     hina      F     B     中部           RC  茶道
10  himari      F     A     関東          EDU  茶道
11     yua      F     A     山陽           SI  茶道
12    riko      F     B     九州           SI  舞踊
13     mei      F     C     東北          GOV  舞踊
14    yota      M     S     東京          EDU  舞踊
15    yuto      M     B     関西           RC  舞踊
16   asahi      M     B     東京          GOV  古典
17    sota      M     B     九州          EDU  古典
18     aoi      F     C     東京           SI  古典
19  haruto      M     C     東北           RC  古典

In [12]:
df.sort_values(by='skill')

KeyError: 'skill'

In [13]:
dataset.sort_values(by='skill')

      name gender skill region presentation  jf
0     yuma      M     A     九州           RC  武道
2   hiroto      M     A     関東          GOV  武道
4     yuna      F     A     関東          EDU  書道
11     yua      F     A     山陽           SI  茶道
10  himari      F     A     関東          EDU  茶道
17    sota      M     B     九州          EDU  古典
16   asahi      M     B     東京          GOV  古典
15    yuto      M     B     関西           RC  舞踊
12    riko      F     B     九州           SI  舞踊
9     hina      F     B     中部           RC  茶道
5   haruto      M     B     中部           SI  書道
7      rin      F     C     関東           RC  書道
6   minato      M     C     山陽          GOV  書道
13     mei      F     C     東北          GOV  舞踊
3   sakura      F     C     関西          EDU  武道
18     aoi      F     C     東京           SI  古典
19  haruto      M     C     東北           RC  古典
8      yui      F     S     関西          GOV  茶道
14    yota      M     S     東京          EDU  舞踊
1      ren      M     S     東京           SI  武道

In [14]:
dataset.sort_values(by=' gender')

KeyError: ' gender'

In [15]:
dataset.sort_values(by='gender')

      name gender skill region presentation  jf
9     hina      F     B     中部           RC  茶道
3   sakura      F     C     関西          EDU  武道
4     yuna      F     A     関東          EDU  書道
7      rin      F     C     関東           RC  書道
8      yui      F     S     関西          GOV  茶道
18     aoi      F     C     東京           SI  古典
10  himari      F     A     関東          EDU  茶道
11     yua      F     A     山陽           SI  茶道
12    riko      F     B     九州           SI  舞踊
13     mei      F     C     東北          GOV  舞踊
17    sota      M     B     九州          EDU  古典
16   asahi      M     B     東京          GOV  古典
15    yuto      M     B     関西           RC  舞踊
14    yota      M     S     東京          EDU  舞踊
0     yuma      M     A     九州           RC  武道
5   haruto      M     B     中部           SI  書道
2   hiroto      M     A     関東          GOV  武道
1      ren      M     S     東京           SI  武道
6   minato      M     C     山陽          GOV  書道
19  haruto      M     C     東北           RC  古典

In [22]:
dataset2 = dataset.sort_values(by='skill')

In [24]:
dataset2.to_csv("newsample4.csv", encoding="shift_jis")

In [25]:
dataset2 = dataset.sort_values(by='skill')

In [26]:
dataset2

      name gender skill region presentation  jf
0     yuma      M     A     九州           RC  武道
2   hiroto      M     A     関東          GOV  武道
4     yuna      F     A     関東          EDU  書道
11     yua      F     A     山陽           SI  茶道
10  himari      F     A     関東          EDU  茶道
17    sota      M     B     九州          EDU  古典
16   asahi      M     B     東京          GOV  古典
15    yuto      M     B     関西           RC  舞踊
12    riko      F     B     九州           SI  舞踊
9     hina      F     B     中部           RC  茶道
5   haruto      M     B     中部           SI  書道
7      rin      F     C     関東           RC  書道
6   minato      M     C     山陽          GOV  書道
13     mei      F     C     東北          GOV  舞踊
3   sakura      F     C     関西          EDU  武道
18     aoi      F     C     東京           SI  古典
19  haruto      M     C     東北           RC  古典
8      yui      F     S     関西          GOV  茶道
14    yota      M     S     東京          EDU  舞踊
1      ren      M     S     東京           SI  武道

In [27]:
df = dataset2

In [28]:
df

      name gender skill region presentation  jf
0     yuma      M     A     九州           RC  武道
2   hiroto      M     A     関東          GOV  武道
4     yuna      F     A     関東          EDU  書道
11     yua      F     A     山陽           SI  茶道
10  himari      F     A     関東          EDU  茶道
17    sota      M     B     九州          EDU  古典
16   asahi      M     B     東京          GOV  古典
15    yuto      M     B     関西           RC  舞踊
12    riko      F     B     九州           SI  舞踊
9     hina      F     B     中部           RC  茶道
5   haruto      M     B     中部           SI  書道
7      rin      F     C     関東           RC  書道
6   minato      M     C     山陽          GOV  書道
13     mei      F     C     東北          GOV  舞踊
3   sakura      F     C     関西          EDU  武道
18     aoi      F     C     東京           SI  古典
19  haruto      M     C     東北           RC  古典
8      yui      F     S     関西          GOV  茶道
14    yota      M     S     東京          EDU  舞踊
1      ren      M     S     東京           SI  武道

In [30]:
male = df[df.gender == "M"]

In [31]:
female = df[df.gender == "F"]

In [32]:
male

      name gender skill region presentation  jf
0     yuma      M     A     九州           RC  武道
2   hiroto      M     A     関東          GOV  武道
17    sota      M     B     九州          EDU  古典
16   asahi      M     B     東京          GOV  古典
15    yuto      M     B     関西           RC  舞踊
5   haruto      M     B     中部           SI  書道
6   minato      M     C     山陽          GOV  書道
19  haruto      M     C     東北           RC  古典
14    yota      M     S     東京          EDU  舞踊
1      ren      M     S     東京           SI  武道

In [33]:
female

      name gender skill region presentation  jf
4     yuna      F     A     関東          EDU  書道
11     yua      F     A     山陽           SI  茶道
10  himari      F     A     関東          EDU  茶道
12    riko      F     B     九州           SI  舞踊
9     hina      F     B     中部           RC  茶道
7      rin      F     C     関東           RC  書道
13     mei      F     C     東北          GOV  舞踊
3   sakura      F     C     関西          EDU  武道
18     aoi      F     C     東京           SI  古典
8      yui      F     S     関西          GOV  茶道

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [42]:
male

      name gender skill region presentation  jf group
0     yuma      M     A     九州           RC  武道     A
2   hiroto      M     A     関東          GOV  武道     B
17    sota      M     B     九州          EDU  古典     C
16   asahi      M     B     東京          GOV  古典     D
15    yuto      M     B     関西           RC  舞踊     A
5   haruto      M     B     中部           SI  書道     B
6   minato      M     C     山陽          GOV  書道     C
19  haruto      M     C     東北           RC  古典     D
14    yota      M     S     東京          EDU  舞踊     A
1      ren      M     S     東京           SI  武道     B

In [43]:
df

      name gender skill region presentation  jf
0     yuma      M     A     九州           RC  武道
2   hiroto      M     A     関東          GOV  武道
4     yuna      F     A     関東          EDU  書道
11     yua      F     A     山陽           SI  茶道
10  himari      F     A     関東          EDU  茶道
17    sota      M     B     九州          EDU  古典
16   asahi      M     B     東京          GOV  古典
15    yuto      M     B     関西           RC  舞踊
12    riko      F     B     九州           SI  舞踊
9     hina      F     B     中部           RC  茶道
5   haruto      M     B     中部           SI  書道
7      rin      F     C     関東           RC  書道
6   minato      M     C     山陽          GOV  書道
13     mei      F     C     東北          GOV  舞踊
3   sakura      F     C     関西          EDU  武道
18     aoi      F     C     東京           SI  古典
19  haruto      M     C     東北           RC  古典
8      yui      F     S     関西          GOV  茶道
14    yota      M     S     東京          EDU  舞踊
1      ren      M     S     東京           SI  武道

In [6]:
df['group'] = int(0)

NameError: name 'df' is not defined

In [46]:
df

      name gender skill region presentation  jf  group
0     yuma      M     A     九州           RC  武道    NaN
2   hiroto      M     A     関東          GOV  武道    NaN
4     yuna      F     A     関東          EDU  書道    NaN
11     yua      F     A     山陽           SI  茶道    NaN
10  himari      F     A     関東          EDU  茶道    NaN
17    sota      M     B     九州          EDU  古典    NaN
16   asahi      M     B     東京          GOV  古典    NaN
15    yuto      M     B     関西           RC  舞踊    NaN
12    riko      F     B     九州           SI  舞踊    NaN
9     hina      F     B     中部           RC  茶道    NaN
5   haruto      M     B     中部           SI  書道    NaN
7      rin      F     C     関東           RC  書道    NaN
6   minato      M     C     山陽          GOV  書道    NaN
13     mei      F     C     東北          GOV  舞踊    NaN
3   sakura      F     C     関西          EDU  武道    NaN
18     aoi      F     C     東京           SI  古典    NaN
19  haruto      M     C     東北           RC  古典    NaN
8      yui      F     S     関西          GOV  茶道    NaN
14    yota      M     S     東京          EDU  舞踊    NaN
1      ren      M     S     東京           SI  武道    NaN

In [47]:
male

      name gender skill region presentation  jf group
0     yuma      M     A     九州           RC  武道     A
2   hiroto      M     A     関東          GOV  武道     B
17    sota      M     B     九州          EDU  古典     C
16   asahi      M     B     東京          GOV  古典     D
15    yuto      M     B     関西           RC  舞踊     A
5   haruto      M     B     中部           SI  書道     B
6   minato      M     C     山陽          GOV  書道     C
19  haruto      M     C     東北           RC  古典     D
14    yota      M     S     東京          EDU  舞踊     A
1      ren      M     S     東京           SI  武道     B

In [48]:
female

      name gender skill region presentation  jf
4     yuna      F     A     関東          EDU  書道
11     yua      F     A     山陽           SI  茶道
10  himari      F     A     関東          EDU  茶道
12    riko      F     B     九州           SI  舞踊
9     hina      F     B     中部           RC  茶道
7      rin      F     C     関東           RC  書道
13     mei      F     C     東北          GOV  舞踊
3   sakura      F     C     関西          EDU  武道
18     aoi      F     C     東京           SI  古典
8      yui      F     S     関西          GOV  茶道

In [2]:
male = df[df.gender == "M"]

NameError: name 'df' is not defined

In [50]:
female = df[df.gender == "F"]

In [51]:
male

      name gender skill region presentation  jf  group
0     yuma      M     A     九州           RC  武道    NaN
2   hiroto      M     A     関東          GOV  武道    NaN
17    sota      M     B     九州          EDU  古典    NaN
16   asahi      M     B     東京          GOV  古典    NaN
15    yuto      M     B     関西           RC  舞踊    NaN
5   haruto      M     B     中部           SI  書道    NaN
6   minato      M     C     山陽          GOV  書道    NaN
19  haruto      M     C     東北           RC  古典    NaN
14    yota      M     S     東京          EDU  舞踊    NaN
1      ren      M     S     東京           SI  武道    NaN

In [52]:
female

      name gender skill region presentation  jf  group
4     yuna      F     A     関東          EDU  書道    NaN
11     yua      F     A     山陽           SI  茶道    NaN
10  himari      F     A     関東          EDU  茶道    NaN
12    riko      F     B     九州           SI  舞踊    NaN
9     hina      F     B     中部           RC  茶道    NaN
7      rin      F     C     関東           RC  書道    NaN
13     mei      F     C     東北          GOV  舞踊    NaN
3   sakura      F     C     関西          EDU  武道    NaN
18     aoi      F     C     東京           SI  古典    NaN
8      yui      F     S     関西          GOV  茶道    NaN

NameError: name 'male' is not defined